"""
SyncTrace — Spatiotemporal Attribution Engine (SAE)
=====================================================
Produces frame x facial-region x audio-band attribution maps explaining
WHERE (spatial), WHEN (temporal) and IN WHAT FREQUENCY BAND (spectral)
the audio-visual inconsistency lives.

Method: gradient-weighted cross-modal attention maps (GradCAM-style) over the
CML embedding manifold, decoded by a lightweight attribution decoder trained
with an IoU objective against the automatic GT masks generated by the
pseudo-forgery generator (severity-controlled replacements).
"""

import torch
from torch import nn


class AttributionDecoder(nn.Module):
    """Lightweight decoder: embedding distance -> (T, R) attribution logits.

    T = number of sampled frames, R = number of spatial regions (e.g.,
    lips / lower_face / full_face) plus one pseudo-channel for the dominant
    audio frequency band.
    """

    def __init__(self, embed_dim: int, num_frames: int = 16,
                 num_regions: int = 3, num_bands: int = 4):
        super().__init__()
        self.num_frames = num_frames
        self.num_regions = num_regions
        self.num_bands = num_bands
        channels = num_regions + num_bands
        self.head = nn.Sequential(
            nn.Linear(embed_dim, channels * num_frames),
            nn.ReLU(),
        )
        self.criterion = nn.BCEWithLogitsLoss()

    def forward(self, delta_embedding: torch.Tensor, gt: torch.Tensor = None):
        """delta_embedding: (B, embed_dim) anomaly direction.

        Returns logits (B, T, R+Bands) and, optionally, BCE loss vs GT.
        """
        logits = self.head(delta_embedding).view(
            delta_embedding.size(0), self.num_frames, -1)
        loss = self.criterion(logits, gt) if gt is not None else None
        return logits, loss


class SpatiotemporalAttributionEngine:
    """End-to-end explainer: builds attribution maps + evaluation helpers."""

    def __init__(self, decoder: AttributionDecoder):
        self.decoder = decoder

    def attribution_map(self, model, audio, video, gt_mask: torch.Tensor = None):
        """Compute cross-modal GradCAM over CML embeddings.

        Returns a dict with visual_heatmap (T, H, W), audio_band_scores (T, B)
        and (if gt given) localization metrics.
        """
        audio.requires_grad_(True)
        video.requires_grad_(True)

        out = model(anchor_a=audio, anchor_v=video,
                    pos_a=audio, pos_v=video, neg_a=audio, neg_v=video,
                    severity=torch.zeros(audio.size(0), device=audio.device))
        anomaly = out["anomaly_score"]

        # gradient of anomaly w.r.t. video frames & audio spectrogram bins
        grad_video = torch.autograd.grad(anomaly.sum(), video,
                                         retain_graph=True)[0]
        grad_audio = torch.autograd.grad(anomaly.sum(), audio)[0]

        # weights per frame: global-average-pool the gradient magnitude
        weights_v = grad_video.flatten(2).abs().mean(2)  # (B, T)
        weights_a = grad_audio.flatten(2).abs().mean(2)  # (B, T)

        # coarse spatial map from gradient activation magnitude
        act = video.abs()
        spatial = (act * grad_video.abs()).flatten(2).mean(2)  # (B, T)
        video_heatmap = (weights_v * spatial).detach()

        # spectral band energy in 4 mel bands per frame
        mel = audio if audio.dim() == 3 else audio.unsqueeze(1)
        _, _, _, F = mel.shape
        band_edges = torch.linspace(0, F, 5, device=mel.device).long()
        band_scores = []
        for i in range(4):
            band = mel[..., band_edges[i]:band_edges[i + 1]]
            band_scores.append(band.flatten(2).abs().mean(2))
        audio_band_scores = torch.stack(band_scores, dim=-1)  # (B, T, 4)
        audio_band_scores = (audio_band_scores * weights_a.unsqueeze(-1)).detach()

        result = {
            "anomaly_score": anomaly.detach(),
            "video_heatmap": video_heatmap,          # (B, T) coarse per-frame
            "audio_band_scores": audio_band_scores,  # (B, T, 4)
        }

        if gt_mask is not None:
            # localization evaluation: predicted top-k frames vs GT frames
            pred_frames = video_heatmap.argsort(descending=True)[:, :8]
            gt_frames = gt_mask.nonzero()[:, 1] if gt_mask.dim() == 2 else gt_mask
            iou = self._frame_iou(pred_frames, gt_frames)
            result["localization_iou"] = iou
        return result

    @staticmethod
    def _frame_iou(pred: torch.Tensor, gt: torch.Tensor) -> float:
        if gt.numel() == 0:
            return 0.0
        pred_set = set(pred[0].tolist())
        gt_set = set(gt.tolist())
        inter = len(pred_set & gt_set)
        union = len(pred_set | gt_set)
        return inter / union if union > 0 else 0.0
